### ISSUE TITLE
What is a "bad pixel"?

### ISSUE THREAD

**Issue by annayqho** [annayqho/AnnaCannon#21]
- flux is infinite
- error is infinite
- error is negative
- do we want to automatically include any of the ASPCAP bad data masks, or are the above three sufficient?

**Comment by davidwhogg** [comment]
In all cases -- whatever you decide (and @mkness can be helpful here) -- set the ivar to 0 (or some well-defined, small value).  Uncertainties should be communicated in the form of ivar (inverse variance)
