### ISSUE TITLE
Ask Morgan to run the code

### ISSUE THREAD

**Issue by annayqho** [annayqho/AnnaCannon#22]

**Comment by davidwhogg** [comment]
get him to record a full log of what he did and what happened, so we have a complete record of what failed and when.

**Comment by annayqho** [comment]
Version now works on both Morgan's computer (Python 3) and mine (Python 2)
Major issues:
- reading in the labels file. apparently the # of columns was inconsistent, the headers were not in a suitable format. is now a more general ASCII file. 
- compatibility with Python 3 - Morgan made the necessary fixes 
- documentation was not all up to date
