### ISSUE TITLE
where is the fit happening?

### ISSUE THREAD

**Issue by davidwhogg** [annayqho/AnnaCannon#30]
In preparation for going over to a Gaussian Process (which will be a subsequent issue), what I want to know is:  What are *all* the locations in the code that need to be changed if (say) we changed the code from a second-order fit to a third-order fit.  Each of these locations should be marked with a comment that says `# specialized to second-order model`.  Then I can just search for those and look at how we will go over to a Gaussian Process.

**Comment by annayqho** [comment]
OK, I think there's only two places (and actually those two places should probably be turned into one place). I added that comment to them. The directory is AnnaCannon/Code/Version1.3/ and the relevant scripts are:
cannon/cannon1_train_model.py
cannon/cannon2_infer_labels.py

**Comment by davidwhogg** [comment]
can you point me to line numbers where the form of the model matters most or is chosen?

also, why are there directories with Version numbers in them?  That's what git does for you -- keep versions!

**Comment by annayqho** [comment]
line 130 in cannon1_train_model
line 26 in cannon2_infer_labels

(and yes, sorry! I will stop making new versions from now on, I've been clinging to a bad pre-Github habit.)
