### ISSUE TITLE
Continuum Normalization Method

### ISSUE THREAD

**Issue by annayqho** [annayqho/AnnaCannon#6]
- Iterative continuum normalization?
- Non-Cannon way: take the spectra of all reference objects, normalize with the 90th percentile method, and from the ensemble of spectra produce two vectors (1-the spectrum, variance) and apply a cut on both to find the continuum. 
- We need to figure out what the best functional form of the continuum fit is.

**Comment by davidwhogg** [comment]
is this issue closed or branched to a new issue?

**Comment by annayqho** [comment]
Branched to a new issue, sorry. HW opened one called "Continuum" which I realized was essentially the same thing, so I just closed this one.
